name: Demo pipeline 

on:
  push:
    branches:
        - main
        - dev   
  pull_request:
    branches: [main, dev]
#   schedule:
#     - cron: "*/1 * * * *"  

jobs:

    setup_job:
        runs-on: ubuntu-latest # macos-latest , windows-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: create file
              run: |
               touch github-action.txt
               echo "from first job" > github-action.txt
               ls -la
               echo hello world
               cat README.md
            - name: upload my artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-file
                path: github-action.txt   
    build_job:
        needs: 
            - setup_job
        runs-on: ubuntu-latest
        steps:
            - name: display hello
              run: echo hello world
            - uses: actions/download-artifact@v5
              with:
                name: my-file  
            - name: Display github-action.txt
              run: cat github-action.txt  
    deploy_job:
        needs: build_job
        runs-on: macos-latest
        steps:
            - name: display hello from mac
              run: echo hello from mac






